spring:
  application:
    name: product
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL_PRODUCT}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true