spring:
  application:
    name: coupon
  datasource:
    url: jdbc:mysql://eks-prod-db-mysql.cluster-cxc2mkao053o.ap-northeast-2.rds.amazonaws.com:3306/prod_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


