apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: member
data:
  DB_HOST: "eks-prod-db-mysql.cluster-cxc2mkao053o.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "prod_db"
