apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-app
  namespace: member
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: 034362047320.dkr.ecr.ap-northeast-2.amazonaws.com/cwave01/back-member:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: member-config
            - secretRef:
                name: member-secret
