apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: member
spec:
  selector:
    app: member
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
