apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  namespace: coupon
spec:
  selector:
    app: coupon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP