# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: product-config
#   namespace: product
# data:
#   APP_ENV: "production"
#   LOG_LEVEL: "info"
#   DATABASE_HOST: "db-service.product.svc.cluster.local"
#   DATABASE_PORT: "5432"
#   REDIS_HOST: "redis-service.product.svc.cluster.local"
#   REDIS_PORT: "6379"
#   API_URL: "https://api.product.com"
#   FEATURE_FLAG: "true"


apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: product
data:
  REDIS_HOST: "clustercfg.dev-elasti-cluster.lbkn6z.apn2.cache.amazonaws.com:6379"
  REDIS_PORT: "6379"
# data:
#   DEV_DB_URL_PRODUCT: "jdbc:mysql://db-service.product.svc.cluster.local:3306/productdb?useSSL=false&serverTimezone=UTC"
